import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url().optional(),
    NEYNAR_API_KEY: z.string().min(1).optional(),
    NEYNAR_WEBHOOK_SECRET: z.string().min(1).optional(),
    NEYNAR_MANAGED_SIGNER: z.string().min(1).optional(),
    GEMINI_API_KEY: z.string().min(1).optional(),
    PYTHON_BACKEND_URL: z.string().url().optional(),
    ADMIN_WALLET_ADDRESS: z.string().min(1).optional(),
    NFT_CONTRACT_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional(),
    NFT_SIGNER_PRIVATE_KEY: z.string().min(1).optional(),
    USDC_CONTRACT_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional(),
    PINATA_JWT: z.string().min(1).optional(),
    BASE_RPC_URL: z.string().url().optional(),
    ALCHEMY_API_KEY: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_APP_NAME: z.string().min(1).optional(),
    NEXT_PUBLIC_CHAIN_ID: z.string().optional(),
    NEXT_PUBLIC_GENERATION_PRICE: z.string().optional(),
    NEXT_PUBLIC_HOSTNAME: z.string().min(1).optional(),
    NEXT_PUBLIC_NEYNAR_CLIENT_ID: z.string().min(1).optional(),
    NEXT_PUBLIC_NFT_CONTRACT_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional(),
    NEXT_PUBLIC_USDC_CONTRACT_ADDRESS: z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional(),
    NEXT_PUBLIC_BASE_RPC_URL: z.string().url().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NEYNAR_API_KEY: process.env.NEYNAR_API_KEY,
    NEYNAR_WEBHOOK_SECRET: process.env.NEYNAR_WEBHOOK_SECRET,
    NEYNAR_MANAGED_SIGNER: process.env.NEYNAR_MANAGED_SIGNER,
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    PYTHON_BACKEND_URL: process.env.PYTHON_BACKEND_URL,
    ADMIN_WALLET_ADDRESS: process.env.ADMIN_WALLET_ADDRESS,
    NFT_CONTRACT_ADDRESS: process.env.NFT_CONTRACT_ADDRESS,
    NFT_SIGNER_PRIVATE_KEY: process.env.NFT_SIGNER_PRIVATE_KEY,
    USDC_CONTRACT_ADDRESS: process.env.USDC_CONTRACT_ADDRESS,
    PINATA_JWT: process.env.PINATA_JWT,
    BASE_RPC_URL: process.env.BASE_RPC_URL,
    ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID,
    NEXT_PUBLIC_GENERATION_PRICE: process.env.NEXT_PUBLIC_GENERATION_PRICE,
    NEXT_PUBLIC_HOSTNAME: process.env.NEXT_PUBLIC_HOSTNAME,
    NEXT_PUBLIC_NEYNAR_CLIENT_ID: process.env.NEXT_PUBLIC_NEYNAR_CLIENT_ID,
    NEXT_PUBLIC_NFT_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS || process.env.NFT_CONTRACT_ADDRESS,
    NEXT_PUBLIC_USDC_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_USDC_CONTRACT_ADDRESS || process.env.USDC_CONTRACT_ADDRESS,
    NEXT_PUBLIC_BASE_RPC_URL: process.env.NEXT_PUBLIC_BASE_RPC_URL || process.env.BASE_RPC_URL,
  },
  skipValidation: true,
})

